[workspace]
members = [
    "rings",
    "xtask",
]

[workspace.dependencies]
#sauron = "0.60.5"
sauron = { path = "../sauron"}
sauron-html-parser = { path = "../sauron/crates/html-parser" }
log = "0.4"
