[workspace]
members = [
    "rings",
    "xtask",
]

[workspace.dependencies]
#sauron = { path = "../sauron"}
sauron = "0.60.6"
#sauron-html-parser = { path = "../sauron/crates/html-parser" }
sauron-html-parser = "0.60.6"
log = "0.4"
